ALTER TABLE "BotConfig" ADD COLUMN IF NOT EXISTS "autoScanEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BotConfig" ADD COLUMN IF NOT EXISTS "autoScanIntervalMin" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "BotConfig" ADD COLUMN IF NOT EXISTS "autoScanMinScore" INTEGER NOT NULL DEFAULT 80;
